<a href="https://colab.research.google.com/github/kevinyangnz/deep-rl-2048/blob/main/deep_rl_2048.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import random
import numpy as np

In [ ]:
NROW = 4
NCOL = 4

In [ ]:
class Game2048:
  def __init__(self, nrow=NROW, ncol=NCOL):
    self.board = np.zeros((NROW, NCOL), dtype=int)
    self.generate_new_num()
    self.generate_new_num()

  def check_game_over(self):
    """
    Check if the game is over given that we have a full board
    """
    # Check rows
    for row in range(NROW):
      prev_tile = 0
      for col in range(NCOL):
        tile = self.board[row][col]
        if tile == prev_tile:
          return False
        prev_tile = tile

    # Check columns
    a = self.board.transpose()
    for row in range(NROW):
      prev_tile = 0
      for col in range(NCOL):
        tile = a[row][col]
        if tile == prev_tile:
          return False
        prev_tile = tile

    return True

  def random_empty_tile(self):
    """
    Picks a random empty tile from the board.
    """
    # Find all empty tiles
    empty_tiles = []
    for i in range(len(self.board)):
      for j in range(len(self.board)):
        if self.board[i][j] == 0:
          empty_tiles.append([i, j])

    # If there are no more empty tiles, check if the game is over
    if len(empty_tiles) == 0:
      game_over = self.check_game_over()
      if game_over:
        return None, None
      else:
        return -1, -1

    # Return a random empty tile
    random_row, random_col = random.choice(empty_tiles)
    return random_row, random_col

  def generate_new_num(self):
    """
    Generate a new random number (2 or 4) and find an empty tile to place it on.
    """
    # Generate random numbers and empty tile
    new_num = 2 if random.random() < 0.9 else 4
    random_row, random_col = self.random_empty_tile()

    # Stop the game or continue if applicable
    if random_row is None or random_col is None:
        print("Game Over!")
        print(self.board)
        return
    elif random_row == -1 or random_col == -1:
      pass
    else:
      self.board[random_row][random_col] = new_num

  def move_left(self):
    """
    Returns the new board state after a left movement.
    """
    # Shift all tiles to the left
    for row in range(NROW):
      empty_space = 0
      for col in range(NCOL):
        tile = self.board[row][col]
        if tile == 0:
          empty_space += 1
        elif empty_space > 0:
          self.board[row][col-empty_space] = tile
          self.board[row][col] = 0

      # Add only non-zero values
      new_tiles = []
      for val in self.board[row]:
        if val != 0:
          new_tiles.append(val)

      # Merge the tiles to the left
      prev_tile = 0
      i = 0
      while i < len(new_tiles):
        tile = new_tiles[i]
        if tile == prev_tile:
          new_tiles[i-1] = tile * 2
          new_tiles.pop(i)
          prev_tile = 0
        else:
          prev_tile = tile
          i += 1

      # Append empty tiles
      while len(new_tiles) < NCOL:
        new_tiles.append(0)

      # Update row
      self.board[row] = new_tiles

    self.generate_new_num()

  def move_right(self):
    """
    Returns the new board state after a right movement.
    """
    self.board = self.board[:, ::-1]
    self.move_left()
    self.board = self.board[:, ::-1]

  def move_up(self):
    """
    Returns the new board state after an up movement.
    """
    self.board = self.board.transpose()
    self.move_left()
    self.board = self.board.transpose()


  def move_down(self):
    """
    Returns the new board state after a down movement.
    """
    self.board = self.board.transpose()[:, ::-1]
    self.move_left()
    self.board = self.board[:, ::-1].transpose()



In [ ]:
game = Game2048(nrow=NROW, ncol=NCOL)
print(game.board)

[[0 0 0 0]
 [0 0 0 0]
 [0 4 0 2]
 [0 0 0 0]]
